// singleton class
// share the location
#include <opencv2/imgproc/imgproc.hpp>
#include <pthread.h>
#include "StereoView.h"

class Global {

private:
    // eye position from EyeTracking class
    cv::Point *position;
    // eye position depth
    int *depth;

    // depth image generated from StereoView class
    cv::Mat *depthImg;
    
    // raw image from the camera, default use the cam0
    cv::Mat *rawImg;

    // running status
    bool* running;
    pthread_mutex_t start;
    // eye position from EyeTracking class
    // share with Cube class to compute the dynamic view matrix
    Global();
    // TODO: delete the space generated by new
public:
    inline static Global& getInstance() {
        static Global instance;
        return instance;        
    }
    void setPosition(cv::Point posIn);
    void setPosition(int x, int y);
    cv::Point getPosition();
    void setRawImg(cv::Mat& raw);
    void setDepthImg(cv::Mat& img3D);
    void getDepthData(int row, int col);
    bool getRunningStatus();
    void setRunningStatus(bool val);
    void setEyeDepth(float val);
    inline int getEyeDepth() {
        return *depth;
    }
};
